use tree_green;
-- Create role
INSERT INTO role(code,name,createby,createdate,modifiedby,modifieddate) VALUES('ADMIN','Quản trị','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO role(code,name,createby,createdate,modifiedby,modifieddate) VALUES('SELLER','Người bán hàng','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO role(code,name,createby,createdate,modifiedby,modifieddate) VALUES('USER','Người dùng','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

INSERT INTO user(username,password,full_name,status,createby,createdate,modifiedby,modifieddate) VALUES('admin','$2a$10$TMkrd3LKZDtJpXnbRZ8oKOxTvYc0MSUymS0e07T9yjVUAefYEBRpC','Nguyễn Văn Hiếu','ACTIVE','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO user(username,password,full_name,status,createby,createdate,modifiedby,modifieddate) VALUES('seller','$2a$10$TMkrd3LKZDtJpXnbRZ8oKOxTvYc0MSUymS0e07T9yjVUAefYEBRpC','Nguyễn Trường Đình','ACTIVE','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO user(username,password,full_name,status,createby,createdate,modifiedby,modifieddate) VALUES('user','$2a$10$TMkrd3LKZDtJpXnbRZ8oKOxTvYc0MSUymS0e07T9yjVUAefYEBRpC','Trần Đình Danh','ACTIVE','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

INSERT INTO user_role(user_id,role_id) VALUES (1,1);
INSERT INTO user_role(user_id,role_id) VALUES (2,2);
INSERT INTO user_role(user_id,role_id) VALUES (3,3);

INSERT INTO cart(user_id,total_price,createby,createdate,modifiedby,modifieddate)
VALUES (3,0.0,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

INSERT INTO shop(name,avatar,description,user_id,createby,createdate,modifiedby,modifieddate)
VALUES ('Shop xanh Phan Rang','https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?size=626&ext=jpg','3 đời nhà tôi bán cây',2,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

-- Create category
INSERT INTO category(code,name,createby,createdate,modifiedby,modifieddate) VALUES ('DAY-LEO','Cây dây leo','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO category(code,name,createby,createdate,modifiedby,modifieddate) VALUES ('TAN-LA','Cây xanh tán lá','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO category(code,name,createby,createdate,modifiedby,modifieddate) VALUES ('SEN-DA','Sen đá','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO category(code,name,createby,createdate,modifiedby,modifieddate) VALUES ('THAN-TO','Cây thân to','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());
INSERT INTO category(code,name,createby,createdate,modifiedby,modifieddate) VALUES ('HOA','Hoa','Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

-- Create product
INSERT INTO product(code,name,image,price,quantity,short_description,description,category_id,shop_id,createby,createdate,modifiedby,modifieddate)
VALUES
    ('sp01','Cây lưu ly phương Đông','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887277/h7xdk1s1xzm3hxj4bdf8.jpg',2704000.0,27,'Một loại cây có hoa nhỏ và thơm, thường được trồng để làm cảnh hoặc để lấy hoa trang trí.','Là một loại cây có nguồn gốc từ phương Đông, có tên khoa học là Cymbidium spp. và thuộc họ lan. Cây có thể cao đến 1 mét, có hoa nhỏ màu trắng, và thơm ngát. Cây lưu ly thường được trồng để làm cảnh hoặc để lấy hoa trang trí, và có thể trồng được cả trong chậu và ngoài trời.',1,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp02','Sen đá','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887336/coldqu3crtfw0gq6y2dp.jpg',2704000.0,27,'Một loại cây thủy sinh có hoa tuyệt đẹp, thường được trồng trong bể cá hoặc hồ nuôi cá.','Là một loại cây thủy sinh có nguồn gốc từ châu Á, có tên khoa học là Cryptocoryne spp. và thuộc họ rau răm. Cây có thể cao đến 60 cm, có hoa tuyệt đẹp với nhiều màu sắc khác nhau, từ trắng, hồng đến đỏ. Sen đá thường được trồng trong bể cá hoặc hồ nuôi cá để tạo ra một môi trường sống tự nhiên cho cá và để trang trí.',3,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp03','Kiểng tuyết xanh','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887354/ezc4g4u82urbcwlhjfvw.jpg',2704000.0,27,'Một loại cây cảnh có hoa và lá màu xanh đặc biệt, thường được trồng trong chậu để trang trí trong nhà.','Là một loại cây cảnh có nguồn gốc từ Trung Quốc, có tên khoa học là Chlorophytum comosum và thuộc họ Asparagaceae. Cây có lá màu xanh đặc biệt, hình dạng giống như dây leo, có hoa nhỏ màu trắng. Kiểng tuyết xanh thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng, và có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp04','Sứ mọng nước','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887370/yfiqu9tgy6xg0xcomxbd.png',2704000.0,27,'Một loại cây có hoa và lá đẹp, thường được trồng trong bể nước hoặc hồ cá để làm cảnh.','Là một loại cây cảnh có nguồn gốc từ Nam Mỹ, có tên khoa học là Syngonium podophyllum và thuộc họ Araceae. Cây có lá hình trái tim, màu xanh lá cây hoặc xanh nâu và thường được trồng trong chậu để làm cảnh trong nhà. Sứ mọng nước có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp05','Cọ núi','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887386/vwzhbvg3orodi4ntqyu9.jpg',2704000.0,27,'Một loại cây có lá dài và hoa thơm, thường được trồng để làm cảnh hoặc để trang trí ngoài trời.','Là một loại cây có nguồn gốc từ vùng núi cao ở Trung Quốc, có tên khoa học là Rhapis excelsa và thuộc họ Palmae. Cây có thân nhỏ, lá màu xanh đậm và được sắp xếp đều quanh thân cây. Cọ núi thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng, và có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp06','Bạch dương','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887402/cnhlzcyhbquijryjf2l6.jpg',2704000.0,27,'Một loại cây có hoa tím đẹp, thường được trồng để làm cảnh hoặc để trang trí.','Là một loại cây cảnh có nguồn gốc từ Trung Quốc, có tên khoa học là Aglaonema spp. và thuộc họ Araceae. Cây có lá màu xanh đậm và trắng và thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng. Bạch dương có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp07','Gỗ nến','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887426/gookvrmjtuqjvji7nmeh.png',2704000.0,27,'Một loại cây có lá và hoa đẹp, thường được trồng để làm cảnh hoặc để trang trí trong nhà.','Là một loại cây có nguồn gốc từ Nam Mỹ, có tên khoa học là Euphorbia ingens và thuộc họ Euphorbiaceae. Cây có thân to và lá màu xanh đậm. Gỗ nến thường được trồng để làm cảnh trong nhà hoặc ngoài trời, và có thể được sử dụng để làm cây chống cát hoặc trang trí.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp08','Xương rồng tròn','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887447/uttsejipyw3g9russjee.jpg',2704000.0,27,'Một loại cây xanh đặc biệt với thân và lá hình mũi tên, thường được trồng để làm cảnh hoặc để trang trí ngoài trời.','Là một loại cây cảnh có nguồn gốc từ vùng núi cao của Trung Mỹ, có tên khoa học là Cactaceae spp. và thuộc họ Cactaceae. Cây có thân dài và lá màu xanh đặc biệt, có gai trên thân cây. Xương rồng thường được trồng để làm cảnh trong nhàhoặc ngoài trời, và có khả năng chịu khô và nắng nóng, thích hợp với khí hậu khô cằn.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp09','Cây kapoke','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887464/di1574jotz7ksiccjwgv.jpg',2704000.0,27,'Một loại cây có hoa đẹp, thường được trồng để làm cảnh hoặc để trang trí.','Là một loại cây cảnh có nguồn gốc từ Trung Mỹ và Nam Mỹ, có tên khoa học là Ceiba pentandra và thuộc họ Bombacaceae. Cây có thân to và lá màu xanh nhạt. Cây kapoke thường được trồng để làm cảnh trong nhà hoặc ngoài trời, và có thể được sử dụng để làm cây bóng mát.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp10','Ráy mía cào','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887481/kt2rhenwhqmvjq8pdfgq.jpg',2704000.0,27,'Một loại cây có hoa và lá đẹp, thường được trồng để làm cảnh hoặc để trang trí.','Là một loại cây cảnh có nguồn gốc từ châu Phi, có tên khoa học là Sansevieria cylindrica và thuộc họ Asparagaceae. Cây có lá màu xanh nhạt, hình trụ, dài và thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng. Ráy mía cào có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp11','Cây cầu nguyện','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887496/akgfw1puowsmt8je20ld.jpg',2704000.0,27,'Một loại cây có hoa nhỏ và đẹp, thường được trồng để làm cảnh hoặc để trang trí trong nhà.',' Là một loại cây cảnh có nguồn gốc từ vùng núi cao của Đông Nam Á, có tên khoa học là Maranta spp. và thuộc họ Marantaceae. Cây có lá màu xanh đậm, hình trái tim và thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng. Cây cầu nguyện có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp12','Lựu cảnh','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887517/wyggloakwvuqjzsmk1vy.jpg',2704000.0,27,'Một loại cây có hoa và quả đẹp, thường được trồng để làm cảnh hoặc để trang trí trong nhà.','Là một loại cây cảnh có nguồn gốc từ Trung Quốc, có tên khoa học là Punica granatum và thuộc họ Lythraceae. Cây có hoa đỏ hoặc cam và trái lựu hình cầu. Lựu cảnh thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp13','Hoa tử đinh hương','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887536/f67yqbpquqynqsd6oqjg.jpg',2704000.0,27,'Một loại hoa thơm và đẹp, thường được trồng để trang trí trong nhà hoặc ngoài trời.','Là một loại cây có nguồn gốc từ Địa Trung Hải, có tên khoa học là Lavandula angustifolia và thuộc họ Lamiaceae. Cây có hoa màu tím và có mùi thơm đặc trưng. Hoa tử đinh hương thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà, và được sử dụng để sản xuất tinh dầu tự nhiên.',5,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp14','Hoa tử đằng','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887536/f67yqbpquqynqsd6oqjg.jpg',2704000.0,27,'Một loại hoa đẹp với màu sắc đa dạng, thường được trồng để làm cảnh hoặc để trang trí.','Là một loại cây có nguồn gốc từ châu Âu và châu Á, có tên khoa học là Digitalis purpurea và thuộc họ Plantaginaceae. Cây có hoa màu tím hoặc hồng, hình ống, dài và mọc thành từng chùm. Hoa tử đằng thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà, và có thể được sử dụng để chữa bệnh tim.',5,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp15','Măng tây mạng nhện','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887582/lgfp4hoknnlxpwewmxqt.jpg',2704000.0,27,'Một loại cây có lá và hoa đẹp, thường được trồng để làm cảnh hoặc để trang trí trong nhà.','Là một loại cây có nguồn gốc từ châu Phi, có tên khoa học là Chlorophytum comosum và thuộc họ Asparagaceae. Cây có lá màu xanh nhạt, hình dài, chằng chịt và thường được trồng trong chậu để làm cảnh trong nhà hoặc văn phòng. Măng tây mạng nhện có khả năng lọc không khí và giúp tạo ra một môi trường sống lành mạnh.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp16','Cây Măng tây','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887601/devzw8lf1dm87dwf0lje.jpg',2704000.0,27,'Một loại cây có lá và quả đẹp, thường được trồng để làm cảnh hoặc để ăn.','Là một loại cây có nguồn gốc từ châu Phi, có tên khoa học là Begonia spp. và thuộc họ Begoniaceae. Cây có hoa màu trắng, đỏ hoặc hồng và lá màu xanh nhạt. Cây Măng tây thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp17','Trăng hoa','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887623/zbm1yanffnfzckobs3j8.png',2704000.0,27,'Một loại hoa có mùi thơm đặc trưng, thường được trồng để trang trí trong nhà hoặc ngoài trời.','Là một loại cây có nguồn gốc từ châu Á, có tên khoa học là Gardenia jasminoides và thuộc họ Rubiaceae. Cây có hoa màu trắng và mùi thơm đặc trưng. Trăng hoa thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà, và được sử dụng để sản xuất nước hoa và mỹ phẩm.',5,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp18','Hoa giấy hồng','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887646/axnndpzqgn0giettd5vi.jpg',2704000.0,27,'Một loại hoa đẹp và dễ trồng, thường được trồng để làm cảnh hoặc để trang trí.','Là một loại cây có nguồn gốc từ châu Á, có tên khoa học là Bougainvillea spp. và thuộc họ Nyctaginaceae. Cây có hoa màu hồng, đỏ hoặc tím và lá màu xanh đậm. Hoa giấy hồng thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà, và có thể được sử dụng để làm hàng rào hoặc bức tường xanh.',5,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp19','Ráy xanh','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887660/kswshpjgmgifgy3jnit6.jpg',2704000.0,27,'Một loại cây có lá đẹp và màu sắc đa dạng, thường được trồng để làm cảnh hoặc để trang trí trong nhà.','Là một loại cây cảnh có nguồn gốc từ châu Phi, có tên khoa học là Zamioculcas zamiifolia và thuộc họ Araceae. Cây có lá màu xanh đậm, bóng và đặc trưng là rất bền và dễ chăm sóc. Ráy xanh thường được trồng trong nhà, văn phòng hay các không gian nội thất khác để tạo ra một không gian xanh tươi, thư giãn.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp20','Cay xanh uốn cong','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887715/hgmwwxmbl2sua4kjkrnr.jpg',2704000.0,27,'Một loại cây có hoa và lá đẹp, thường được trồng để làm cảnh hoặc để trang trí trong nhà.','Là một loại cây có nguồn gốc từ châu Phi và châu Á, có tên khoa học là Ficus elastica và thuộc họ Moraceae. Cây có lá màu xanh đậm và dày, thường có hình uốn cong hoặc xoắn vặn đặc biệt. Cay xanh uốn cong thường được trồng để làm cảnh trong nhà, văn phòng hay các không gian nội thất khác để tạo ra một không gian xanh tươi, thư giãn.',4,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    ('sp21','Đuôi rồng xanh','https://res.cloudinary.com/dtsfnikj0/image/upload/v1681887731/riel6fkvwdgnjwmalyxx.jpg',2704000.0,27,'Một loại cây có lá xanh đặc biệt với hình dạng giống như đuôi rồng, thường được trồng để làm cảnh hoặc để trang trí ngoài trời.','Là một loại cây có nguồn gốc từ Nam Mỹ, có tên khoa học là Epiphyllum spp. và thuộc họ Cactaceae. Cây có hoa màu trắng, đỏ hoặc hồng và thường mọc trên các nhánh thân dài và mảnh mai. Đuôi rồng xanh thường được trồng để làm cảnh trong sân vườn hoặc vườn trước nhà, và có thể được sử dụng để làm cây leo hoặc tạo hình trong các không gian cảnh quan.',2,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());

-- Create product view
INSERT INTO product_view(view,product_id,createby,createdate,modifiedby,modifieddate)
VALUES
    (1,1,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,2,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,3,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,4,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,5,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,6,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,7,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,8,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,9,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,10,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,11,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,12,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,13,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,14,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,15,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,16,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,17,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,18,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,19,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,20,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP()),
    (1,21,'Developers',CURRENT_TIMESTAMP(),'Developers',CURRENT_TIMESTAMP());