export const dataFake = [
  {
    id: 1,
    name: "flower flower green",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "popular",
  },
  {
    id: 2,
    name: "flower green",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-12-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "winter",
  },
  {
    id: 3,
    name: "flower",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-10-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "popular",
  },
  {
    id: 4,
    name: "flower",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-14-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "winter",
  },
  {
    id: 5,
    name: "flower flower",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-14-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "cactuses",
  },
  {
    id: 6,
    name: "flower green",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "cactuses",
  },
  {
    id: 7,
    name: "flower",
    price: 229000,
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-12-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "green",
  },
  {
    id: 8,
    name: "flower",
    des:" Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue.",
    price: 229000,
    img: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-10-img.jpg",
    img1: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img2: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    img3: "http://mauweb.monamedia.net/fiorello/wp-content/uploads/2018/06/shop-13-img.jpg",
    type: "green",
  },
 
];
